# Generated by Django 4.0.3 on 2022-03-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'dishes'},
        ),
    ]
